import React, { useCallback, useEffect, useState } from 'react';
import { AlertCircle, Copy, Key, Plus, RefreshCw, Terminal } from 'lucide-react';
import { getCoreApiUrl } from '../lib/coreApi';
import { requestCore } from '../lib/coreRequest';

interface Props { showToast?: (msg: string) => void; }
interface ApiKey { id: number; name: string; description?: string | null; product_code: string; key_prefix: string; status: string; created_at: string; revoked_at?: string | null; last_used_at?: string | null; }

export const CoreDeveloperApiView: React.FC<Props> = ({ showToast = () => {} }) => {
  const [keys, setKeys] = useState<ApiKey[]>([]); const [open, setOpen] = useState(false); const [name, setName] = useState(''); const [secret, setSecret] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const r = await fetch(`${getCoreApiUrl()}/api/v1/developer/api-keys`, { credentials: 'include' }); const b = await r.json(); if (!r.ok) throw new Error(b?.detail || 'Gagal mengambil API keys.'); setKeys(b.items || []); } catch (e) { showToast(e instanceof Error ? e.message : 'Gagal mengambil API keys.'); } finally { setLoading(false); } }, [showToast]);
  useEffect(() => { void load(); }, [load]);
  const create = async (e: React.FormEvent) => { e.preventDefault(); try { const b = await requestCore<{ api_key: string; }>(`/api/v1/developer/api-keys`, { method: 'POST', body: JSON.stringify({ name, product_code: 'PQC_API' }) }); setSecret(b.api_key); setName(''); await load(); showToast('API key dibuat oleh NusaSec-Core.'); } catch (e) { showToast(e instanceof Error ? e.message : 'Gagal membuat API key.'); } };
  const revoke = async (id: number) => { try { await requestCore(`/api/v1/developer/api-keys/${id}/revoke`, { method: 'POST' }); await load(); showToast('API key dicabut di Core.'); } catch (e) { showToast(e instanceof Error ? e.message : 'Gagal mencabut key.'); } };
  const copy = (v: string) => { void navigator.clipboard.writeText(v); showToast('Tersalin ke clipboard.'); };
  return <div id="developer-api-view" className="flex-1 overflow-y-auto bg-[#f8fafc] dark:bg-slate-950 px-4 sm:px-8 py-6 max-w-7xl mx-auto w-full space-y-6"><div className="flex flex-col sm:flex-row justify-between gap-3"><div><div className="text-[11px] uppercase font-bold font-mono text-slate-500">NusaSec Developer Plane</div><h1 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">PQC API Keys &amp; Telemetry</h1><p className="text-xs sm:text-sm text-slate-500">Secret hanya muncul sekali; hash dan lifecycle dikelola oleh Core.</p></div><div className="flex gap-2"><button onClick={() => void load()} className="px-3 py-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl text-xs font-semibold flex gap-2"><RefreshCw className={loading ? 'w-4 h-4 animate-spin' : 'w-4 h-4'} /> Refresh</button><button onClick={() => { setSecret(null); setOpen(true); }} className="px-4 py-2 bg-slate-900 dark:bg-blue-600 text-white rounded-xl text-xs font-semibold flex gap-2"><Plus className="w-4 h-4" /> Buat Kunci API</button></div></div><div className="space-y-3">{keys.map(k => <div key={k.id} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-4 flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div><div className="flex flex-wrap gap-2 items-center"><strong className="text-sm text-slate-900 dark:text-white">{k.name}</strong><span className="font-mono text-[11px] px-2 py-0.5 rounded bg-slate-100 dark:bg-slate-800 text-slate-500">{k.key_prefix}</span><span className={`text-[10px] px-2 py-0.5 rounded-full ${k.status === 'ACTIVE' ? 'bg-emerald-50 text-emerald-700' : 'bg-rose-50 text-rose-700'}`}>{k.status}</span></div><div className="text-[11px] text-slate-400 mt-1">Dibuat: {new Date(k.created_at).toLocaleString()} • Terakhir digunakan: {k.last_used_at ? new Date(k.last_used_at).toLocaleString() : 'Belum digunakan'}</div></div>{k.status === 'ACTIVE' && <button onClick={() => void revoke(k.id)} className="px-3 py-1.5 bg-rose-50 text-rose-700 border border-rose-200 rounded-lg text-xs font-semibold">Cabut Kunci</button>}</div>)}</div><div className="bg-slate-950 text-white rounded-2xl p-5 font-mono text-xs"><div className="flex justify-between border-b border-slate-800 pb-2 text-slate-400"><span className="flex gap-2 items-center"><Terminal className="w-4 h-4" /> API Example</span><button onClick={() => copy('curl -X POST https://api.nusasec.com/api/v1/pqc/kem/encapsulate -H "Authorization: Bearer nsc_..."')}><Copy className="w-4 h-4" /></button></div><pre className="mt-3 overflow-x-auto text-blue-300">curl -X POST https://api.nusasec.com/api/v1/pqc/kem/encapsulate \\
  -H "Authorization: Bearer nsc_..."</pre></div>{open && <div className="fixed inset-0 z-50 bg-black/60 flex items-center justify-center p-4"><div className="w-full max-w-lg bg-white dark:bg-slate-900 rounded-2xl p-6 space-y-4"><div className="flex justify-between"><h2 className="font-bold text-slate-900 dark:text-white flex gap-2 items-center"><Key className="w-5 h-5 text-blue-600" /> Buat API Key</h2><button onClick={() => setOpen(false)}>✕</button></div>{secret ? <><div className="bg-amber-50 border border-amber-200 rounded-xl p-4 text-xs text-amber-900"><div className="font-bold flex gap-2 items-center"><AlertCircle className="w-4 h-4" /> Simpan sekarang</div><p className="mt-1">Secret ini hanya ditampilkan sekali.</p></div><div className="bg-slate-950 text-emerald-400 rounded-xl p-3 font-mono text-xs break-all flex gap-2"><span>{secret}</span><button className="ml-auto" onClick={() => copy(secret)}><Copy className="w-4 h-4" /></button></div><button onClick={() => setOpen(false)} className="w-full py-2 bg-slate-900 text-white rounded-xl text-sm">Selesai</button></> : <form onSubmit={create} className="space-y-3"><input required value={name} onChange={e => setName(e.target.value)} placeholder="Nama API Key" className="w-full px-3 py-2 rounded-xl border bg-slate-50 dark:bg-slate-950"/><button className="w-full py-2.5 bg-blue-600 text-white rounded-xl font-semibold">Generate</button></form>}</div></div>}</div>;
};
