import React, { useCallback, useEffect, useState } from 'react';
import { AlertTriangle, RefreshCw, ShieldCheck } from 'lucide-react';
import { getCoreApiUrl } from '../lib/coreApi';

export const CoreAttackPathsView: React.FC<{ showToast?: (msg:string)=>void }> = ({ showToast=(_message: string)=>{} }) => {
 const [items,setItems]=useState<any[]>([]); const [severity,setSeverity]=useState('all'); const [loading,setLoading]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(`${getCoreApiUrl()}/api/v1/product/attack-paths?limit=100`,{credentials:'include'});const b=await r.json();if(!r.ok)throw new Error(b?.detail||'Gagal mengambil attack paths.');setItems(b.items||[]);}catch(e){showToast(e instanceof Error?e.message:'Gagal mengambil attack paths.')}finally{setLoading(false)}},[showToast]);
 useEffect(()=>{void load()},[load]); const filtered=items.filter(x=>severity==='all'||x.severity===severity);
 return <div className="flex-1 overflow-y-auto bg-[#f8fafc] dark:bg-slate-950 px-4 sm:px-8 py-6 max-w-7xl mx-auto w-full space-y-6"><div className="flex justify-between gap-3"><div><div className="text-[11px] uppercase font-bold tracking-wider font-mono text-slate-500">NusaSec Risk Graph</div><h1 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">Attack Paths</h1><p className="text-xs sm:text-sm text-slate-500">Path dan node dihitung dari scan terbaru Core.</p></div><button onClick={()=>void load()} className="p-2.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800"><RefreshCw className={loading?'w-4 h-4 animate-spin':'w-4 h-4'}/></button></div><div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-3"><div className="text-xs text-slate-400 mb-2">Criticality filter</div><div className="flex flex-wrap gap-1.5">{['all','CRITICAL','HIGH','MEDIUM','LOW'].map(v=><button key={v} onClick={()=>setSeverity(v)} className={`px-3 py-1.5 rounded-lg text-xs font-semibold ${severity===v?'bg-slate-900 dark:bg-blue-600 text-white':'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300'}`}>{v}</button>)}</div></div><div className="space-y-4">{filtered.map(path=><div key={path.path_id} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3"><div className="flex gap-2 items-center"><AlertTriangle className="w-4 h-4 text-rose-600"/><span className="text-[10px] font-mono bg-rose-50 text-rose-700 px-2 py-0.5 rounded">{path.severity}</span><span className="text-xs font-mono text-slate-400">risk {path.risk_score}</span></div><ShieldCheck className="w-4 h-4 text-blue-600"/></div><p className="text-sm font-semibold text-slate-900 dark:text-white mt-2">{path.description || 'Attack path terdeteksi'}</p><div className="mt-4 space-y-2">{(path.nodes||[]).map((node:any,i:number)=><div key={node.external_id+i} className="flex items-center gap-2"><div className="w-2 h-2 rounded-full bg-rose-500"/><div className="flex-1 p-3 rounded-xl border border-slate-200 dark:border-slate-800"><div className="text-xs font-bold text-slate-900 dark:text-white">{node.name || node.external_id}</div><div className="text-[11px] text-slate-500">{node.provider} • {node.asset_type} • {node.criticality}</div></div>{i < path.nodes.length-1 && <div className="text-slate-400">↓</div>}</div>)}</div></div>)}</div></div>;
};
