import React, { useCallback, useEffect, useState } from 'react';
import { CheckCircle2, Play, RefreshCw, ShieldCheck, Sparkles, Zap } from 'lucide-react';
import { getCoreApiUrl } from '../lib/coreApi';
import { requestCore } from '../lib/coreRequest';

export const CoreMigrationCenterView: React.FC<{ showToast?: (msg: string) => void }> = ({ showToast = () => {} }) => {
  const [mode, setMode] = useState<'HYBRID' | 'FULL_PQC'>('HYBRID'); const [overview, setOverview] = useState<any>(null); const [plan, setPlan] = useState<any>(null); const [simulation, setSimulation] = useState<any>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  const request = useCallback(async <T,>(path: string, init: RequestInit = {}) => requestCore<T>(path, init), []);
  const load = useCallback(async () => { setLoading(true); try { setOverview(await request('/api/v1/migration-center/overview')); setError(null); } catch (e) { setError(e instanceof Error ? e.message : 'Gagal mengambil migration overview.'); } finally { setLoading(false); } }, [request]);
  useEffect(() => { void load(); }, [load]);
  const createAndSimulate = async () => { setLoading(true); try { const created = await request<any>('/api/v1/migration-center/plans', { method: 'POST', body: JSON.stringify({ current_algorithm: 'ECDH Secp256r1 + RSA-2048', target_algorithm: mode === 'HYBRID' ? 'X25519 + ML-KEM-768 + ML-DSA-65' : 'ML-KEM-768 + ML-DSA-65', plan: { mode, requested_by: 'customer-ui' } }) }); setPlan(created); const sim = await request<any>(`/api/v1/migration-center/plans/${created.id}/simulate`, { method: 'POST' }); setSimulation(sim); await load(); showToast('Migration plan dibuat dan simulasi dijalankan oleh Core.'); } catch (e) { showToast(e instanceof Error ? e.message : 'Simulasi migration gagal.'); } finally { setLoading(false); } };
  const promote = async () => { if (!plan?.id) return; try { const result = await request<any>(`/api/v1/migration-center/plans/${plan.id}/transition`, { method: 'POST', body: JSON.stringify({ target_state: 'PROMOTED', approval_ref: `customer-ui:${Date.now()}` }) }); setPlan((p: any) => ({ ...p, state: result.state })); await load(); showToast('Migration plan dipromosikan melalui lifecycle Core.'); } catch (e) { showToast(e instanceof Error ? e.message : 'Promosi gagal.'); } };
  return <div id="migration-center-view" className="flex-1 overflow-y-auto bg-[#f8fafc] dark:bg-slate-950 px-4 sm:px-8 py-6 max-w-7xl mx-auto w-full space-y-6"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4"><div><div className="text-[11px] uppercase tracking-wider font-bold text-slate-500 font-mono">NusaSec Quantum Migration Engine</div><h1 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">Post-Quantum Migration Center &amp; Sandbox</h1><p className="text-xs sm:text-sm text-slate-500">Plan, simulate, snapshot dan promote dijalankan oleh Core.</p></div><button onClick={() => void load()} className="px-3 py-2 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-xs font-semibold flex items-center gap-2"><RefreshCw className={loading ? 'w-4 h-4 animate-spin' : 'w-4 h-4'} /> Refresh</button></div>
    {error && <div className="p-4 rounded-xl border border-rose-200 bg-rose-50 text-rose-700 text-sm">{error}</div>}
    <div className="grid grid-cols-1 md:grid-cols-2 gap-5"><div className="bg-white border border-slate-200 dark:bg-slate-900 dark:border-slate-800 rounded-2xl p-6 space-y-4"><div className="text-xs font-bold uppercase text-rose-600">BEFORE</div><div className="rounded-xl bg-rose-50/60 dark:bg-rose-950/20 p-4"><div className="text-[10px] text-slate-400">CLASSICAL BASELINE</div><div className="font-mono font-bold text-slate-900 dark:text-white">ECDH Secp256r1 + RSA-2048</div><div className="text-xs text-rose-600 mt-1">Quantum-vulnerable asymmetric primitives</div></div></div><div className="bg-slate-950 text-white rounded-2xl p-6 space-y-4 border border-purple-800"><div className="text-xs font-bold uppercase text-purple-300 flex items-center gap-2"><Sparkles className="w-4 h-4" /> AFTER</div><div className="rounded-xl bg-purple-900/40 p-4"><div className="text-[10px] text-purple-300">TARGET MODE</div><div className="font-mono font-bold">{mode === 'HYBRID' ? 'X25519 + ML-KEM-768 + ML-DSA-65' : 'ML-KEM-768 + ML-DSA-65'}</div><div className="text-xs text-emerald-400 mt-1">NIST-aligned post-quantum target</div></div></div></div>
    <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5"><div className="flex flex-wrap gap-2"><button onClick={() => setMode('HYBRID')} className={`px-3 py-2 rounded-xl text-xs font-semibold ${mode === 'HYBRID' ? 'bg-purple-600 text-white' : 'bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-200'}`}>Hybrid</button><button onClick={() => setMode('FULL_PQC')} className={`px-3 py-2 rounded-xl text-xs font-semibold ${mode === 'FULL_PQC' ? 'bg-purple-600 text-white' : 'bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-200'}`}>Full PQC</button><button onClick={() => void createAndSimulate()} className="ml-auto px-4 py-2 rounded-xl bg-slate-900 dark:bg-blue-600 text-white text-xs font-semibold flex items-center gap-2"><Play className="w-4 h-4" /> Jalankan Simulasi</button></div></div>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3">{[['Plans', overview?.plans?.total ?? 0], ['Blocked', overview?.plans?.blocked ?? 0], ['Readiness', `${overview?.readiness_pct ?? 0}%`], ['Current Plan', plan?.state || '—']].map(([k,v]) => <div key={String(k)} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-4"><span className="text-[11px] text-slate-500">{k}</span><div className="text-xl font-extrabold text-slate-900 dark:text-white mt-1">{v}</div></div>)}</div>
    {simulation && <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5"><h3 className="font-bold text-slate-900 dark:text-white flex items-center gap-2"><ShieldCheck className="w-4 h-4 text-emerald-600" /> Simulation Result</h3><div className="mt-3 grid grid-cols-1 md:grid-cols-3 gap-3 text-sm"><div>Status: <strong>{simulation.status}</strong></div><div>Findings: <strong>{simulation.findings?.length ?? 0}</strong></div><div>Metrics: <strong>{Object.keys(simulation.metrics || {}).length}</strong></div></div></div>}
    {plan?.id && plan?.state !== 'PROMOTED' && <div className="flex justify-end"><button onClick={() => void promote()} className="px-5 py-2.5 rounded-xl bg-emerald-600 text-white text-xs font-bold flex items-center gap-2"><CheckCircle2 className="w-4 h-4" /> Promosikan via Core Lifecycle</button></div>}
  </div>;
};
