import React, { useCallback, useEffect, useState } from 'react';
import { ExternalLink, RefreshCw, Scale } from 'lucide-react';
import { getCoreApiUrl } from '../lib/coreApi';

export const CoreRegulatoryIntelligenceView: React.FC<{ showToast?: (msg: string) => void }> = ({ showToast = () => {} }) => {
  const [items, setItems] = useState<any[]>([]); const [changes, setChanges] = useState<any[]>([]); const [profileStatus, setProfileStatus] = useState<any[]>([]); const [selected, setSelected] = useState<any>(null); const [loading, setLoading] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const [c,a,ch] = await Promise.all([fetch(`${getCoreApiUrl()}/api/v1/regulatory/catalog`, {credentials:'include'}).then(r=>r.json()), fetch(`${getCoreApiUrl()}/api/v1/regulatory/applicability`, {credentials:'include'}).then(r=>r.json()), fetch(`${getCoreApiUrl()}/api/v1/regulatory/changes`, {credentials:'include'}).then(r=>r.json())]); setItems(c.instruments || []); setProfileStatus(a.items || []); setChanges(ch.items || []); } catch(e) { showToast(e instanceof Error ? e.message : 'Gagal mengambil regulatory intelligence.'); } finally { setLoading(false); } }, [showToast]);
  useEffect(() => { void load(); }, [load]);
  const applicability = (key:string) => profileStatus.find(x=>x.instrument_key===key);
  return <div id="regulatory-intelligence-view" className="flex-1 overflow-y-auto bg-[#f8fafc] dark:bg-slate-950 px-4 sm:px-8 py-6 max-w-7xl mx-auto w-full space-y-6"><div className="flex justify-between gap-3"><div><div className="text-[11px] uppercase tracking-wider font-bold text-slate-500 font-mono">NusaSec Regulatory Intelligence Plane</div><h1 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">Regulatory Intelligence &amp; Legal Obligations</h1><p className="text-xs sm:text-sm text-slate-500">Catalog dan applicability dari source resmi yang dikelola Core.</p></div><button onClick={()=>void load()} className="p-2.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800"><RefreshCw className={loading?'w-4 h-4 animate-spin':'w-4 h-4'}/></button></div><div className="grid grid-cols-1 md:grid-cols-3 gap-4">{items.map(inst=>{const a=applicability(inst.id);return <button key={inst.id} onClick={()=>setSelected(inst)} className={`p-5 rounded-2xl border text-left ${selected?.id===inst.id?'bg-slate-900 text-white border-slate-900':'bg-white dark:bg-slate-900 border-slate-200 dark:border-slate-800'}`}><div className="flex justify-between"><span className="text-[10px] font-mono px-2 py-0.5 rounded bg-slate-100 dark:bg-slate-800">{inst.jurisdiction}</span><span className="text-[10px] font-mono opacity-70">{inst.id}</span></div><h3 className="font-bold text-sm mt-3">{inst.title}</h3><div className="text-xs mt-3 opacity-80">{a?.status || 'NOT_EVALUATED'} • {a?.confidence || '—'}</div></button>})}</div>{selected&&<div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-6 space-y-5"><div className="flex flex-col sm:flex-row justify-between gap-3"><div><div className="flex items-center gap-2"><Scale className="w-5 h-5 text-blue-600"/><h3 className="text-lg font-bold text-slate-900 dark:text-white">{selected.title}</h3></div><p className="text-xs text-slate-500 mt-1">{selected.type} • {selected.jurisdiction}</p></div><a href={selected.official_source_url} target="_blank" rel="noreferrer" className="inline-flex gap-2 items-center text-xs text-blue-600">Sumber Resmi <ExternalLink className="w-3.5 h-3.5"/></a></div><p className="text-xs text-slate-500">Status source: {selected.verification_status} • Coverage: {selected.coverage_status}</p><div className="border-t border-slate-100 dark:border-slate-800 pt-4"><h4 className="text-xs font-bold uppercase font-mono text-slate-500 mb-3">Recent Regulatory Changes</h4><div className="space-y-2">{changes.filter(x=>x.instrument_key===selected.id).slice(0,8).map(x=><div key={x.change_key} className="p-3 rounded-xl border border-slate-200 dark:border-slate-800"><div className="font-semibold text-sm text-slate-900 dark:text-white">{x.title}</div><div className="text-xs text-slate-500 mt-1">{x.summary}</div></div>)}</div></div></div>}</div>;
};
