import React, { useCallback, useEffect, useState } from 'react';
import { Atom, Binary, RefreshCw } from 'lucide-react';
import { getCoreApiUrl } from '../lib/coreApi';

export const CorePqcReadinessView: React.FC<{ onNavigateToMigration?:()=>void; showToast?: (msg:string)=>void }> = ({ onNavigateToMigration=()=>{}, showToast=()=>{} }) => {
 const [items,setItems]=useState<any[]>([]); const [overview,setOverview]=useState<any>(null); const [loading,setLoading]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const [c,o]=await Promise.all([fetch(`${getCoreApiUrl()}/api/v1/data-intelligence/catalog?object_type=pqc_asset&limit=500`,{credentials:'include'}).then(r=>r.json()),fetch(`${getCoreApiUrl()}/api/v1/migration-center/overview`,{credentials:'include'}).then(r=>r.json())]);setItems(c.items||[]);setOverview(o)}catch(e){showToast(e instanceof Error?e.message:'Gagal mengambil PQC readiness.')}finally{setLoading(false)}},[showToast]); useEffect(()=>{void load()},[load]);
 return <div id="pqc-readiness-view" className="flex-1 overflow-y-auto bg-[#f8fafc] dark:bg-slate-950 px-4 sm:px-8 py-6 max-w-7xl mx-auto w-full space-y-6"><div className="flex flex-col sm:flex-row justify-between gap-3"><div><div className="text-[11px] uppercase tracking-wider font-bold text-slate-500 font-mono">NusaSec Quantum Plane</div><h1 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">PQC Readiness &amp; CBOM</h1><p className="text-xs sm:text-sm text-slate-500">Inventaris PQC dan migration readiness berasal dari Core.</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="p-2.5 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800"><RefreshCw className={loading?'w-4 h-4 animate-spin':'w-4 h-4'}/></button><button onClick={onNavigateToMigration} className="px-3 py-2 rounded-xl bg-purple-600 text-white text-xs font-semibold flex gap-2"><Binary className="w-4 h-4"/> Migration Center</button></div></div><div className="bg-gradient-to-r from-slate-950 via-purple-950 to-indigo-950 text-white rounded-3xl p-6"><div className="flex items-center gap-2 text-purple-300 text-xs font-mono"><Atom className="w-4 h-4"/> CORE PQC INVENTORY</div><div className="text-2xl sm:text-3xl font-bold mt-2">{overview?.readiness_pct ?? 0}% Migration Readiness</div><div className="text-sm text-purple-200 mt-1">{items.length} cryptographic assets terdeteksi.</div></div><div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b border-slate-200 dark:border-slate-800 text-slate-400"><th className="p-3 text-left">Asset</th><th className="p-3 text-left">Current</th><th className="p-3 text-left">Risk</th><th className="p-3 text-left">Migration</th></tr></thead><tbody>{items.map(r=><tr key={r.object_key} className="border-b border-slate-100 dark:border-slate-800"><td className="p-3 font-semibold text-slate-900 dark:text-white">{r.display_name || r.object_key}</td><td className="p-3 text-slate-500">{r.attributes?.current_algorithm || '—'}</td><td className="p-3 text-slate-500">{r.attributes?.risk_level || '—'}</td><td className="p-3 text-purple-600">{r.attributes?.migration_status || '—'}</td></tr>)}</tbody></table></div></div>;
};
