import React, { useCallback, useEffect, useState } from 'react';
import { Activity, AlertTriangle, CheckCircle2, RefreshCw, ShieldCheck } from 'lucide-react';
import { getCoreApiUrl } from '../lib/coreApi';

interface AnalyticsProps { showToast?: (msg: string) => void; }
interface AnalyticsData { risk?: { score?: number; finding_count?: number; by_severity?: Record<string, number> }; assets?: number; open_remediation?: number; overdue_remediation?: number; trend?: Array<{ recorded_at: string; asset_count: number; finding_count: number }>; business_impact?: { crown_jewel_assets?: number; business_units?: number } }

export const CoreAnalyticsView: React.FC<AnalyticsProps> = ({ showToast = (_msg: string) => {} }) => {
  const [data, setData] = useState<AnalyticsData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const r = await fetch(`${getCoreApiUrl()}/api/v1/product-experience/analytics`, { credentials: 'include' }); const b = await r.json().catch(() => ({})); if (!r.ok) throw new Error(b?.detail || `Core request failed (${r.status})`); setData(b); setError(null); } catch (e) { setError(e instanceof Error ? e.message : 'Gagal mengambil analytics Core.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const max = Math.max(1, ...(data?.trend || []).map(x => x.finding_count || 0));
  return <div className="flex-1 overflow-y-auto bg-[#f8fafc] dark:bg-slate-950 px-4 sm:px-8 py-6 max-w-7xl mx-auto w-full space-y-6">
    <div className="flex items-center justify-between gap-3"><div><div className="text-[11px] uppercase tracking-wider font-bold font-mono text-slate-500">NusaSec Core Analytics</div><h1 className="text-xl sm:text-2xl font-bold text-slate-900 dark:text-white">Security &amp; Workspace Analytics</h1><p className="text-xs sm:text-sm text-slate-500">Metric tenant, posture, remediation dan business impact dari Core.</p></div><button onClick={() => { void load(); showToast('Analytics diperbarui dari NusaSec-Core.'); }} className="px-3 py-2 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-xs font-semibold flex gap-2 items-center"><RefreshCw className={loading ? 'w-4 h-4 animate-spin' : 'w-4 h-4'} /> Refresh</button></div>
    {error && <div className="p-4 rounded-xl border border-rose-200 bg-rose-50 text-rose-700 text-sm">{error}</div>}
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[
      ['Posture Score', data?.risk?.score ?? '—', ShieldCheck], ['Findings', data?.risk?.finding_count ?? 0, AlertTriangle], ['Assets', data?.assets ?? 0, Activity], ['Open Remediation', data?.open_remediation ?? 0, CheckCircle2]
    ].map(([label, value, Icon]: any) => <div key={String(label)} className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5"><div className="flex justify-between text-xs text-slate-500"><span>{label}</span><Icon className="w-4 h-4 text-blue-600" /></div><div className="text-2xl font-extrabold text-slate-900 dark:text-white mt-2">{value}</div></div>)}</div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6"><div className="lg:col-span-2 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5"><h3 className="font-bold text-slate-900 dark:text-white">Finding Trend</h3><div className="h-64 flex items-end gap-3 mt-5">{(data?.trend || []).map((x, i) => { const h = Math.max(4, Math.round((x.finding_count / max) * 100)); return <div key={i} className="flex-1 min-w-8 flex flex-col justify-end items-center gap-2"><div className="w-full max-w-10 bg-blue-600 rounded-t-lg" style={{ height: `${h}%` }} /><span className="text-[10px] text-slate-400 whitespace-nowrap">{new Date(x.recorded_at).toLocaleDateString()}</span></div>; })}</div></div><div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl p-5"><h3 className="font-bold text-slate-900 dark:text-white mb-4">Business Impact</h3><div className="space-y-3 text-sm"><div className="flex justify-between"><span className="text-slate-500">Crown-jewel assets</span><strong>{data?.business_impact?.crown_jewel_assets ?? 0}</strong></div><div className="flex justify-between"><span className="text-slate-500">Business units</span><strong>{data?.business_impact?.business_units ?? 0}</strong></div><div className="flex justify-between"><span className="text-slate-500">Overdue remediation</span><strong>{data?.overdue_remediation ?? 0}</strong></div></div></div></div>
  </div>;
};